server:
  port: 8082

spring:
  application:
    name: merchant-service
  data:
    mongodb:
      uri: mongodb://localhost:27018/merchant

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    registry-with-eureka: true
