server:
  port: 8082

jwt.secret: mysecret
jwt.expiration: 7200000
single_registry_token: 123SINGLE56

spring:
  application:
    name: restaurant-service
  data:
    mongodb:
      uri: mongodb://localhost:27018/restaurant-service


