server:
  port: 8083

jwt.secret: mysecret
jwt.expiration: 7200000
token: 123SINGLE56
authorization_token: 123SINGLE56

spring:
  application:
    name: merchant-service
  data:
    mongodb:
      uri: mongodb://localhost:27018/single-registry


